# -*- coding: utf-8 -*-
"""background_remooval.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1678NZQXYdUqKFucPpPMhsDwtzUl1HJHK
"""

from rembg import remove
from PIL import Image
from google.colab import files
import matplotlib.pyplot as plt
import io

# Upload your image
uploaded = files.upload()
filename = list(uploaded.keys())[0]

# Load image and convert to RGBA to preserve transparency
input_image = Image.open(filename).convert("RGBA")

# Remove background without resizing or compressing
output = remove(input_image)

# Create a new image with white background (to avoid transparency issues)
background = Image.new("RGBA", output.size, (255, 255, 255, 255))  # White background
background.paste(output, mask=output.split()[3])  # Use alpha channel as mask

# Convert to RGB (remove alpha)
final_image = background.convert("RGB")

# Save final image in high quality
output_filename = f"bg_removed_{filename.split('.')[0]}_high_quality.jpg"
final_image.save(output_filename, format='JPEG', quality=100, subsampling=0)

# Show the final result
plt.figure(figsize=(6,6))
plt.imshow(final_image)
plt.axis('off')
plt.title("High-Quality Foreground (Background Removed)")
plt.show()

